//
// Created by Jamie Cotter on 04/02/2022.
//

#ifndef UNTITLED2_ALGORITHMTYPES_H
#define UNTITLED2_ALGORITHMTYPES_H

enum algorithm_type { REACTIVE_BASIC, REACTIVE_MOBILE, PREALLOCATION, PARTITION, PROACTIVE };


#endif //UNTITLED2_ALGORITHMTYPES_H
