//
// Created by Jamie Cotter on 04/03/2022.
//

#ifndef FIRSTHOPMOBILEOFFLOADING_ALGORITHMMODEFLAGS_H
#define FIRSTHOPMOBILEOFFLOADING_ALGORITHMMODEFLAGS_H



#endif //FIRSTHOPMOBILEOFFLOADING_ALGORITHMMODEFLAGS_H
