//
// Created by Jamie Cotter on 04/02/2022.
//

#ifndef UNTITLED2_GENERALCONSTANTS_H
#define UNTITLED2_GENERALCONSTANTS_H

#define NO_NODE_FOUND -1
#define RETURN_TO_MOBILE -1
#define NO_RESERVATION_FOUND -1
#define RESERVATION_NOT_READY -1
#define SERVERS_PER_CLOUDLET 1

#endif //UNTITLED2_GENERALCONSTANTS_H
