//
// Created by Jamie Cotter on 04/02/2022.
//

#ifndef UNTITLED2_PREALLOCATIONCONSTANTS_H
#define UNTITLED2_PREALLOCATIONCONSTANTS_H

const short NO_RESERVATION_FOUND = -1;
const short RESERVATION_NOT_READY = -1;

#endif //UNTITLED2_PREALLOCATIONCONSTANTS_H
